In [52]:
# %%capture
!pip -qq install boto3 pandas

In [53]:
import boto3
import pandas as pd
from io import StringIO

s3 = boto3.client("s3",
                  aws_access_key_id="ASIA3IHXCCLL76JVWYOZ",
                  aws_secret_access_key="y/0XSPMb/PAv+gbEr5xj+7cXNzw72778g6NrNEo+",
                  aws_session_token="IQoJb3JpZ2luX2VjEJn//////////wEaCXVzLXdlc3QtMiJHMEUCIQDGAiAss5VQEHTKOGuNfVAsrEHPxj5p3pGtdXRaUWzCPwIgd7FpxdS/6/LV1OKHcEDlrOUPkgy8ttdhXO9rWTt4q0wqogIIYhABGgw3NzM2MTIyNDU3MTkiDAl9mxzHvUtVvI/0hyr/AVywehfk4O0OpIVEFvJrBhPI71UCVPHN5PBlIT1B4vr7TFduLGS6ne/TlGQe7dRUu0DqG0c8fNzT5wD29NgoELEfTVKE7wji0M4QRJYTxidybVyo4jAn67VbWCCTHe5w/k7XcN1QxATMwgS1Tc0LG/QfaKOfGd7G342lNcHBDubOnylytA/BalZtJ+v7D5swAwqoeAHcVJ8ZsVx3TDhje+dLBybC5zwX2uaUGYpQGs2EhHNsUlHsSegu/vEsTvugfii1JEUKLXztDaRjcq9D9R4w73NFukucONmvHbFcJCYJlnzHIA0Mr4iNCWK5rjUROJWyM4P6nrsSIeIsSMOfXzDG97bOBjqdAa4oUTOoV9rbbxex5twVa+9GOIq/N7uFkuidqxApSDEGve3/iJtfBTz/Gff2+U6duJiMawxeMlPL2ql7b39/UZesJujzOI5JX+Y0TWaFNNy8VgKb6OobyexpEcbiLbVB8krbCcsKg/4WEoH+yHauvnEOzG+8c2CtJArAuDJdG3NdN/q6on279Q5hnvY8I35J1bFEIaSehq6eenAKzbg=",
                  region_name="us-east-1")  
bucket = "c0957259"
key="airbnb/raw_data/listings.csv"

obj = s3.get_object(Bucket=bucket, Key=key)
df = pd.read_csv(obj["Body"])

In [54]:
df.isnull().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [55]:
# Filling no reviews to 0
df["last_review"] = pd.to_datetime(df["last_review"])
df["review_year"] = df['last_review'].dt.year
df["review_month"] = df['last_review'].dt.month
df["review_day"] = df['last_review'].dt.day
df[["review_year", "review_month", "review_day"]] = (df[["review_year", "review_month", "review_day"]].fillna(0))
df = df.drop(columns="last_review")
df["reviews_per_month"] = df["reviews_per_month"].fillna(0)

In [56]:
df.info(1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  reviews_per_month               48895 non-null  float64
 13  calculated_host_listings_count  48895 non-null  int64
 14  availability_365                48895 non-null  int64
 15  review_year                     48895 non-null  float64
 16  review_month                    48895 non-null  float64
 17  review_day                      48895 non-null  float64
dtypes: float64(6), int64(7), object(5)
memory usage: 6.7+ MB

In [57]:
# Handling outliers by removing them
q1 = df["price"].quantile(0.25)
q3 = df["price"].quantile(0.75)
iqr = q3 - q1

df = df[(df["price"] >= q1 - 1.5*iqr) & (df["price"] <= q3 +1.5*iqr)]

In [58]:
# Encoding categorical variables
df = pd.get_dummies(df, columns=["neighbourhood", "neighbourhood_group", "room_type"], drop_first=True)

In [59]:
df.head(5)

,id,name,host_id,host_name,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,...,neighbourhood_Windsor Terrace,neighbourhood_Woodhaven,neighbourhood_Woodlawn,neighbourhood_Woodside,neighbourhood_group_Brooklyn,neighbourhood_group_Manhattan,neighbourhood_group_Queens,neighbourhood_group_Staten Island,room_type_Private room,room_type_Shared room
0,2539,Clean & quiet apt home by the park,2787,John,40.64749,-73.97237,149,1,9,0.21,...,False,False,False,False,True,False,False,False,True,False
1,2595,Skylit Midtown Castle,2845,Jennifer,40.75362,-73.98377,225,1,45,0.38,...,False,False,False,False,False,True,False,False,False,False
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,40.80902,-73.94190,150,3,0,0.00,...,False,False,False,False,False,True,False,False,True,False
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,40.68514,-73.95976,89,1,270,4.64,...,False,False,False,False,True,False,False,False,False,False
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,40.79851,-73.94399,80,10,9,0.10,...,False,False,False,False,False,True,False,False,False,False

In [60]:
df.info(1)

<class 'pandas.core.frame.DataFrame'>
Index: 45923 entries, 0 to 48894
Data columns (total 239 columns):
 #    Column                                    Dtype
---   ------                                    -----
 0    id                                        int64
 1    name                                      object
 2    host_id                                   int64
 3    host_name                                 object
 4    latitude                                  float64
 5    longitude                                 float64
 6    price                                     int64
 7    minimum_nights                            int64
 8    number_of_reviews                         int64
 9    reviews_per_month                         float64
 10   calculated_host_listings_count            int64
 11   availability_365                          int64
 12   review_year                               float64
 13   review_month                              float64
 14   review_day                                float64
 15   neighbourhood_Arden Heights               bool
 16   neighbourhood_Arrochar                    bool
 17   neighbourhood_Arverne                     bool
 18   neighbourhood_Astoria                     bool
 19   neighbourhood_Bath Beach                  bool
 20   neighbourhood_Battery Park City           bool
 21   neighbourhood_Bay Ridge                   bool
 22   neighbourhood_Bay Terrace                 bool
 23   neighbourhood_Bay Terrace, Staten Island  bool
 24   neighbourhood_Baychester                  bool
 25   neighbourhood_Bayside                     bool
 26   neighbourhood_Bayswater                   bool
 27   neighbourhood_Bedford-Stuyvesant          bool
 28   neighbourhood_Belle Harbor                bool
 29   neighbourhood_Bellerose                   bool
 30   neighbourhood_Belmont                     bool
 31   neighbourhood_Bensonhurst                 bool
 32   neighbourhood_Bergen Beach                bool
 33   neighbourhood_Boerum Hill                 bool
 34   neighbourhood_Borough Park                bool
 35   neighbourhood_Breezy Point                bool
 36   neighbourhood_Briarwood                   bool
 37   neighbourhood_Brighton Beach              bool
 38   neighbourhood_Bronxdale                   bool
 39   neighbourhood_Brooklyn Heights            bool
 40   neighbourhood_Brownsville                 bool
 41   neighbourhood_Bull's Head                 bool
 42   neighbourhood_Bushwick                    bool
 43   neighbourhood_Cambria Heights             bool
 44   neighbourhood_Canarsie                    bool
 45   neighbourhood_Carroll Gardens             bool
 46   neighbourhood_Castle Hill                 bool
 47   neighbourhood_Castleton Corners           bool
 48   neighbourhood_Chelsea                     bool
 49   neighbourhood_Chinatown                   bool
 50   neighbourhood_City Island                 bool
 51   neighbourhood_Civic Center                bool
 52   neighbourhood_Claremont Village           bool
 53   neighbourhood_Clason Point                bool
 54   neighbourhood_Clifton                     bool
 55   neighbourhood_Clinton Hill                bool
 56   neighbourhood_Co-op City                  bool
 57   neighbourhood_Cobble Hill                 bool
 58   neighbourhood_College Point               bool
 59   neighbourhood_Columbia St                 bool
 60   neighbourhood_Concord                     bool
 61   neighbourhood_Concourse                   bool
 62   neighbourhood_Concourse Village           bool
 63   neighbourhood_Coney Island                bool
 64   neighbourhood_Corona                      bool
 65   neighbourhood_Crown Heights               bool
 66   neighbourhood_Cypress Hills               bool
 67   neighbourhood_DUMBO                       bool
 68   neighbourhood_Ditmars Steinway            bool
 69   neighbourhood_Dongan Hills                bool
 70   neighbourhood_Douglaston                  bool
 71   neighbourhood_Downtown Brooklyn           bool
 72   neighbourhood_Dyker Heights               bool
 73   neighbourhood_East Elmhurst               bool
 74   neighbourhood_East Flatbush               bool
 75   neighbourhood_East Harlem                 bool
 76   neighbourhood_East Morrisania             bool
 77   neighbourhood_East New York               bool
 78   neighbourhood_East Village                bool
 79   neighbourhood_Eastchester                 bool
 80   neighbourhood_Edenwald                    bool
 81   neighbourhood_Edgemere                    bool
 82   neighbourhood_Elmhurst                    bool
 83   neighbourhood_Eltingville                 bool
 84   neighbourhood_Emerson Hill                bool
 85   neighbourhood_Far Rockaway                bool
 86   neighbourhood_Fieldston                   bool
 87   neighbourhood_Financial District          bool
 88   neighbourhood_Flatbush                    bool
 89   neighbourhood_Flatiron District           bool
 90   neighbourhood_Flatlands                   bool
 91   neighbourhood_Flushing                    bool
 92   neighbourhood_Fordham                     bool
 93   neighbourhood_Forest Hills                bool
 94   neighbourhood_Fort Greene                 bool
 95   neighbourhood_Fort Hamilton               bool
 96   neighbourhood_Fresh Meadows               bool
 97   neighbourhood_Glendale                    bool
 98   neighbourhood_Gowanus                     bool
 99   neighbourhood_Gramercy                    bool
 100  neighbourhood_Graniteville                bool
 101  neighbourhood_Grant City                  bool
 102  neighbourhood_Gravesend                   bool
 103  neighbourhood_Great Kills                 bool
 104  neighbourhood_Greenpoint                  bool
 105  neighbourhood_Greenwich Village           bool
 106  neighbourhood_Grymes Hill                 bool
 107  neighbourhood_Harlem                      bool
 108  neighbourhood_Hell's Kitchen              bool
 109  neighbourhood_Highbridge                  bool
 110  neighbourhood_Hollis                      bool
 111  neighbourhood_Holliswood                  bool
 112  neighbourhood_Howard Beach                bool
 113  neighbourhood_Howland Hook                bool
 114  neighbourhood_Huguenot                    bool
 115  neighbourhood_Hunts Point                 bool
 116  neighbourhood_Inwood                      bool
 117  neighbourhood_Jackson Heights             bool
 118  neighbourhood_Jamaica                     bool
 119  neighbourhood_Jamaica Estates             bool
 120  neighbourhood_Jamaica Hills               bool
 121  neighbourhood_Kensington                  bool
 122  neighbourhood_Kew Gardens                 bool
 123  neighbourhood_Kew Gardens Hills           bool
 124  neighbourhood_Kingsbridge                 bool
 125  neighbourhood_Kips Bay                    bool
 126  neighbourhood_Laurelton                   bool
 127  neighbourhood_Lighthouse Hill             bool
 128  neighbourhood_Little Italy                bool
 129  neighbourhood_Little Neck                 bool
 130  neighbourhood_Long Island City            bool
 131  neighbourhood_Longwood                    bool
 132  neighbourhood_Lower East Side             bool
 133  neighbourhood_Manhattan Beach             bool
 134  neighbourhood_Marble Hill                 bool
 135  neighbourhood_Mariners Harbor             bool
 136  neighbourhood_Maspeth                     bool
 137  neighbourhood_Melrose                     bool
 138  neighbourhood_Middle Village              bool
 139  neighbourhood_Midland Beach               bool
 140  neighbourhood_Midtown                     bool
 141  neighbourhood_Midwood                     bool
 142  neighbourhood_Mill Basin                  bool
 143  neighbourhood_Morningside Heights         bool
 144  neighbourhood_Morris Heights              bool
 145  neighbourhood_Morris Park                 bool
 146  neighbourhood_Morrisania                  bool
 147  neighbourhood_Mott Haven                  bool
 148  neighbourhood_Mount Eden                  bool
 149  neighbourhood_Mount Hope                  bool
 150  neighbourhood_Murray Hill                 bool
 151  neighbourhood_Navy Yard                   bool
 152  neighbourhood_Neponsit                    bool
 153  neighbourhood_New Brighton                bool
 154  neighbourhood_New Dorp                    bool
 155  neighbourhood_New Dorp Beach              bool
 156  neighbourhood_New Springville             bool
 157  neighbourhood_NoHo                        bool
 158  neighbourhood_Nolita                      bool
 159  neighbourhood_North Riverdale             bool
 160  neighbourhood_Norwood                     bool
 161  neighbourhood_Oakwood                     bool
 162  neighbourhood_Olinville                   bool
 163  neighbourhood_Ozone Park                  bool
 164  neighbourhood_Park Slope                  bool
 165  neighbourhood_Parkchester                 bool
 166  neighbourhood_Pelham Bay                  bool
 167  neighbourhood_Pelham Gardens              bool
 168  neighbourhood_Port Morris                 bool
 169  neighbourhood_Port Richmond               bool
 170  neighbourhood_Prince's Bay                bool
 171  neighbourhood_Prospect Heights            bool
 172  neighbourhood_Prospect-Lefferts Gardens   bool
 173  neighbourhood_Queens Village              bool
 174  neighbourhood_Randall Manor               bool
 175  neighbourhood_Red Hook                    bool
 176  neighbourhood_Rego Park                   bool
 177  neighbourhood_Richmond Hill               bool
 178  neighbourhood_Richmondtown                bool
 179  neighbourhood_Ridgewood                   bool
 180  neighbourhood_Riverdale                   bool
 181  neighbourhood_Rockaway Beach              bool
 182  neighbourhood_Roosevelt Island            bool
 183  neighbourhood_Rosebank                    bool
 184  neighbourhood_Rosedale                    bool
 185  neighbourhood_Rossville                   bool
 186  neighbourhood_Schuylerville               bool
 187  neighbourhood_Sea Gate                    bool
 188  neighbourhood_Sheepshead Bay              bool
 189  neighbourhood_Shore Acres                 bool
 190  neighbourhood_Silver Lake                 bool
 191  neighbourhood_SoHo                        bool
 192  neighbourhood_Soundview                   bool
 193  neighbourhood_South Beach                 bool
 194  neighbourhood_South Ozone Park            bool
 195  neighbourhood_South Slope                 bool
 196  neighbourhood_Springfield Gardens         bool
 197  neighbourhood_Spuyten Duyvil              bool
 198  neighbourhood_St. Albans                  bool
 199  neighbourhood_St. George                  bool
 200  neighbourhood_Stapleton                   bool
 201  neighbourhood_Stuyvesant Town             bool
 202  neighbourhood_Sunnyside                   bool
 203  neighbourhood_Sunset Park                 bool
 204  neighbourhood_Theater District            bool
 205  neighbourhood_Throgs Neck                 bool
 206  neighbourhood_Todt Hill                   bool
 207  neighbourhood_Tompkinsville               bool
 208  neighbourhood_Tottenville                 bool
 209  neighbourhood_Tremont                     bool
 210  neighbourhood_Tribeca                     bool
 211  neighbourhood_Two Bridges                 bool
 212  neighbourhood_Unionport                   bool
 213  neighbourhood_University Heights          bool
 214  neighbourhood_Upper East Side             bool
 215  neighbourhood_Upper West Side             bool
 216  neighbourhood_Van Nest                    bool
 217  neighbourhood_Vinegar Hill                bool
 218  neighbourhood_Wakefield                   bool
 219  neighbourhood_Washington Heights          bool
 220  neighbourhood_West Brighton               bool
 221  neighbourhood_West Farms                  bool
 222  neighbourhood_West Village                bool
 223  neighbourhood_Westchester Square          bool
 224  neighbourhood_Westerleigh                 bool
 225  neighbourhood_Whitestone                  bool
 226  neighbourhood_Williamsbridge              bool
 227  neighbourhood_Williamsburg                bool
 228  neighbourhood_Willowbrook                 bool
 229  neighbourhood_Windsor Terrace             bool
 230  neighbourhood_Woodhaven                   bool
 231  neighbourhood_Woodlawn                    bool
 232  neighbourhood_Woodside                    bool
 233  neighbourhood_group_Brooklyn              bool
 234  neighbourhood_group_Manhattan             bool
 235  neighbourhood_group_Queens                bool
 236  neighbourhood_group_Staten Island         bool
 237  room_type_Private room                    bool
 238  room_type_Shared room                     bool
dtypes: bool(224), float64(6), int64(7), object(2)
memory usage: 15.4+ MB

In [61]:
# dropping columns name and host_name
df = df.drop(columns=["name"])
df = df.drop(columns=["host_name"])

In [62]:

# Feature selection
x = df.drop("price", axis=1)
y = df["price"]

In [63]:
# train-test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [64]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import mean_absolute_error, r2_score

In [65]:
!pip -qq install xgboost

In [66]:
from xgboost import XGBRegressor

In [84]:
# model = LinearRegression()
# model.fit(X_train, y_train)

# train_preds = model.predict(X_train)
# test_preds = model.predict(X_test)

# train_mae = mean_absolute_error(y_train, train_preds)
# train_r2 = r2_score(y_train, train_preds)

# test_mae = mean_absolute_error(y_test, test_preds)
# test_r2 = r2_score(y_test, test_preds)

# print("Train MAE:", train_mae)
# print("Train R2:", train_r2)
# print("Test MAE:", test_mae)
# print("Test R2:", test_r2)

In [85]:
# model = RandomForestRegressor()
# model.fit(X_train, y_train)

# train_preds = model.predict(X_train)
# test_preds = model.predict(X_test)

# train_mae = mean_absolute_error(y_train, train_preds)
# train_r2 = r2_score(y_train, train_preds)

# test_mae = mean_absolute_error(y_test, test_preds)
# test_r2 = r2_score(y_test, test_preds)

# print("Train MAE:", train_mae)
# print("Train R2:", train_r2)
# print("Test MAE:", test_mae)
# print("Test R2:", test_r2)

In [86]:
# model = XGBRegressor(
#     objective="reg:squarederror",
#     n_estimators=100,
#     learning_rate=0.1,
#     max_depth=6,
#     random_state=42
# )

# model.fit(X_train, y_train)

# train_preds = model.predict(X_train)
# test_preds = model.predict(X_test)

# train_mae = mean_absolute_error(y_train, train_preds)
# train_r2 = r2_score(y_train, train_preds)

# test_mae = mean_absolute_error(y_test, test_preds)
# test_r2 = r2_score(y_test, test_preds)

# print("Train MAE:", train_mae)
# print("Train R2:", train_r2)
# print("Test MAE:", test_mae)
# print("Test R2:", test_r2)

In [72]:
!pip -qq install mlflow

In [73]:
import mlflow
import mlflow.sklearn
import mlflow.xgboost

from mlflow.models import infer_signature

mlflow.set_tracking_uri("file:./mlruns")
mlflow.set_experiment("airbnb-price-prediction")

c:\Users\borut\AppData\Local\Programs\Python\Python312\Lib\site-packages\mlflow\tracking\_tracking_service\utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
2026/04/01 22:19:01 INFO mlflow.tracking.fluent: Experiment with name 'airbnb-price-prediction' does not exist. Creating a new experiment.

<Experiment: artifact_location='file:c:/Users/borut/Downloads/SoftTools-A2/mlruns/986950131085387398', creation_time=1775096341761, experiment_id='986950131085387398', last_update_time=1775096341761, lifecycle_stage='active', name='airbnb-price-prediction', tags={}, workspace='default'>

In [ ]:
# defining the function to log one model at a time 
def log_model_run(model_name, model, params):
    with mlflow.start_run(run_name=model_name):
        mlflow.log_params(params)

        model.fit(X_train, y_train)

        train_preds = model.predict(X_train)
        test_preds = model.predict(X_test)

        train_mae = mean_absolute_error(y_train, train_preds)
        train_r2 = r2_score(y_train, train_preds)
        test_mae = mean_absolute_error(y_test, test_preds)
        test_r2 = r2_score(y_test, test_preds)
        
        mlflow.log_metrics({
            "train_mae": train_mae,
            "train_r2": train_r2,
            "test_mae": test_mae,
            "test_r2": test_r2
        })

        signature = infer_signature(X_train, train_preds)

        if model_name == "XGBoost":
            mlflow.xgboost.log_model(
                xgb_model=model,
                name="model",
                signature=signature,
                input_example=X_train.iloc[:3]
            )
        else:
            mlflow.sklearn.log_model(
                sk_model=model,
                name="model",
                signature=signature,
                input_example=X_train.iloc[:3]

            )

        return {
            "model_name": model_name,
            "train_mae": train_mae,
            "train_r2": train_r2,
            "test_mae": test_mae,
            "test_r2": test_r2
        }

In [75]:
results = []

lr_model= LinearRegression()
results.append(log_model_run(
    "LinearRegression",
    lr_model,
    lr_model.get_params()
))

rf_model = RandomForestRegressor(random_state=42)
results.append(log_model_run(
    "RandomForestRegressor",
    rf_model,
    rf_model.get_params()
))

xgb_model = XGBRegressor(
    objective="reg:squarederror",
    n_estimators=100,
    learning_rate=0.1,
    max_depth=6,
    random_state=42
)

results.append(log_model_run(
    "XGBoost",
    xgb_model,
    xgb_model.get_params()
))

c:\Users\borut\AppData\Local\Programs\Python\Python312\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
2026/04/01 22:31:50 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1834.89it/s]
c:\Users\borut\AppData\Local\Programs\Python\Python312\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
2026/04/01 22:32:35 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 41.56it/s]
c:\Users\borut\AppData\Local\Programs\Python\Python312\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 3506.94it/s]

In [78]:
# comparing runs 
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by="test_r2", ascending=False)
results_df

              model_name  train_mae  train_r2   test_mae   test_r2
2                XGBoost  29.552122  0.637888  31.454443  0.587240
1  RandomForestRegressor  11.666991  0.941573  31.440158  0.582285
0       LinearRegression  33.957277  0.536202  34.257250  0.525605

In [79]:
# Deciding best model
best_model_name = results_df.iloc[0]["model_name"]

if best_model_name == "LinearRegression":
    best_model = LinearRegression()
elif best_model_name == "RandomForestRegressor":
    best_model = RandomForestRegressor(random_state=42)
else:
    best_model = XGBRegressor(
        objective="reg:squarederror",
        n_estimators=100,
        learning_rate=0.1,
        max_depth=6,
        random_state=42
    )

with mlflow.start_run(run_name=f"{best_model_name}_best_model"):
    best_model.fit(X_train, y_train)
    best_preds = best_model.predict(X_test)
    signature = infer_signature(X_test, best_preds)

    mlflow.log_metric("test_mae", mean_absolute_error(y_test, best_preds))
    mlflow.log_metric("test_r2", r2_score(y_test, best_preds))

    if best_model_name == "XGBoost":
        mlflow.xgboost.log_model(
            xgb_model=best_model,
            name="best_model",
            signature=signature,
            input_example=X_train.iloc[:3],
            registered_model_name="AirbnbPricePredictor"
        )
    else:
        mlflow.sklearn.log_model(
            sk_model=best_model,
            name="best_model",
            signature=signature,
            input_example=X_train.iloc[:3],
            registered_model_name="AirbnbPricePredictor"
        )

c:\Users\borut\AppData\Local\Programs\Python\Python312\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 2332.02it/s]
c:\Users\borut\AppData\Local\Programs\Python\Python312\Lib\site-packages\mlflow\tracking\_model_registry\utils.py:220: FutureWarning: The filesystem model registry backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri)
Successfully registered model 'AirbnbPricePredictor'.
Created version '1' of model 'AirbnbPricePredictor'.

In [ ]:
!mlflow ui

In [82]:
!pip freeze > requirements.txt